site_name: WN CLI Documentation
site_url: https://sjzsdu.github.io/wn/  # 添加站点 URL
site_description: WN CLI tool documentation
site_author: Juzhong Sun

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang: zh
  - minify:
      minify_html: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: zh
          default: true
          name: 中文
          build: true
        - locale: en
          name: English
          build: true

nav:
  - zh:
    - 首页: index.md
    - 命令:
      - WN: wn.md
      - Agent: wn_agent.md
      - AI: wn_ai.md
      - Cache: wn_cache.md
      - Config: wn_config.md
      - Doc: wn_doc.md
      - Git: 
        - 概述: wn_git.md
        - Commit: wn_git_commit.md
        - List: wn_git_list.md
        - Rebase: wn_git_rebase.md
        - 帮助: wn_git_help.md
      - Help: wn_help.md
      - MCP:
        - 概述: wn_mcp.md
        - 服务端: wn_mcp_server.md
        - 客户端: wn_mcp_client.md
        - 帮助: wn_mcp_help.md
      - Pack: wn_pack.md
      - Project: wn_project.md
      - Static: wn_static.md
      - Version: wn_version.md
  - en:
    - Home: index.md
    - Commands:
      - WN: wn.md
      - Agent: wn_agent.md
      - AI: wn_ai.md
      - Cache: wn_cache.md
      - Config: wn_config.md
      - Doc: wn_doc.md
      - Git: 
        - Overview: wn_git.md
        - Commit: wn_git_commit.md
        - List: wn_git_list.md
        - Rebase: wn_git_rebase.md
        - Help: wn_git_help.md
      - Help: wn_help.md
      - MCP:
        - Overview: wn_mcp.md
        - Server: wn_mcp_server.md
        - Client: wn_mcp_client.md
        - Help: wn_mcp_help.md
      - Pack: wn_pack.md
      - Project: wn_project.md
      - Static: wn_static.md
      - Version: wn_version.md

# GitHub Pages 相关配置
repo_name: sjzsdu/wn
repo_url: https://github.com/sjzsdu/wn
edit_uri: edit/main/docs/

# 错误处理
strict: false
