site_name: WN CLI Documentation
site_url: https://sjzsdu.github.io/wn/  # 添加站点 URL
site_description: WN CLI tool documentation
site_author: Juzhong Sun

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang: zh
  - minify:
      minify_html: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: zh
          default: true
          name: 中文
          build: true
        - locale: en
          name: English
          build: true

nav:
  - zh:
    - 首页: index.md
    - 命令:
      - WN: wn.md
      - Agent: agent.md
      - AI: ai.md
      - Config: config.md
      - Doc: doc.md
      - Git: 
        - 概述: git.md
        - Commit: commit.md
        - List: list.md
        - Rebase: rebase.md
      - Pack: pack.md
      - Static: static.md
      - Version: version.md
      - MCP:
        - 概述: mcp.md
        - 服务端: server.md
        - 客户端: client.md
  - en:
    - Home: index.md
    - Commands:
      - WN: wn.md
      - Agent: agent.md
      - AI: ai.md
      - Config: config.md
      - Doc: doc.md
      - Git: 
        - Overview: git.md
        - Commit: commit.md
        - List: list.md
        - Rebase: rebase.md
      - Pack: pack.md
      - Static: static.md
      - Version: version.md
      - MCP:
        - Overview: mcp.md
        - Server: server.md
        - Client: client.md

# GitHub Pages 相关配置
repo_name: sjzsdu/wn
repo_url: https://github.com/sjzsdu/wn
edit_uri: edit/main/docs/

# 错误处理
strict: true
