name: Deploy Documentation
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: pip
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mkdocs mkdocs-material mkdocs-static-i18n mkdocs-minify-plugin
          
      - name: Generate Cobra docs
        run: |
          mkdir -p docs
          pwd
          ls -la
          go mod tidy
          go run main.go doc
          ls -la docs/
          
      - name: Fix doc links
        run: |
          cd docs
          for lang in zh en; do
            cd $lang
            for file in *.md; do
              if [ -f "$file" ]; then
                sed -i 's/wn_//g' "$file"
                sed -i 's/git_\([a-z]*\).md/\1.md/g' "$file"
              fi
            done
            # 修复语言切换链接
            if [ "$lang" = "zh" ]; then
              sed -i 's/README.en.md/\/en\//g' index.md
            fi
            cd ..
          done
          
      - name: Clean doc filenames
        run: |
          cd docs
          for lang in zh en; do
            cd $lang
            for file in wn_*.md; do
              if [ -f "$file" ]; then
                mv "$file" "${file#wn_}"
              fi
            done
            cd ..
          done
          
      - name: Check docs generation
        run: |
          if [ ! -f "docs/zh/index.md" ] || [ ! -f "docs/en/index.md" ]; then
            echo "Documentation generation failed"
            exit 1
          fi
        
      - name: Check docs structure
        run: |
            echo "Checking docs structure..."
            ls -R docs/
        
      - name: Deploy docs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mkdocs gh-deploy --force --strict