name: Deploy Documentation
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: pip
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-static-i18n mkdocs-minify-plugin
          
      - name: Generate Cobra docs
        run: |
          mkdir -p docs
          go run main.go doc
        
      - name: Check docs generation
        run: |
          if [ ! -f "docs/index.md" ]; then
            echo "Documentation generation failed"
            exit 1
          fi
        
      - name: Deploy docs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mkdocs gh-deploy --force --strict